server:
  port: 8099

api:
  yahoo-finance:
    domain: 'https://query1.finance.yahoo.com/v7/finance/quote?symbols={$symbol}&crumb={$crumb}'
    history-domain: 'https://query1.finance.yahoo.com/v8/finance/chart/{$symbol}?period1=1&period2=30000000000&interval=1d&events=history'

database: 
  db-name: "final_project"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)


management:
  server:
    port: 7001
    address: localhost
  endpoints:
    web:
      exposure:
        include: "*"

